---
env:
  TZ: Europe/London
task:
  name: Kernel compilation
  timeout_in: 60m
  container:
    image: nexgang/ubuntu:latest
    stateful: true
    greedy: true
    cpu: 4
    memory: 16G
  Setting-up-environment_script:
    - dir
    - ls
    - mkdir working
    - cd working
    - sudo apt-get update -y
    - sudo apt-get install make build-essential libncurses-dev bison flex
      libssl-dev libelf-dev ccache -y
    - sudo apt-get -y install locales
    - export LC_CTYPE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
  Cloning-clang_script:
    - mkdir clang
    - cd clang
    - bash <(curl -s
      https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman)
      -S=latest
    - sudo apt-get install libelf-dev libarchive-tools -y
    - bash -c "$(wget -O -
      https://gist.githubusercontent.com/dakkshesh07/240736992abf0ea6f0ee1d8acb57a400/raw/e97b505653b123b586fc09fda90c4076c8030732/patch-for-old-glibc.sh)"
    - dir
    - cd ..
  Building-kernel_script:
    - git clone https://github.com/aospa-lunaa/android_kernel_realme_sm7325 --depth=1 -b topaz-standalone kernel
    - cd kernel
    - wget https://raw.githubusercontent.com/rk134/topaz-compiler/main/buildkernel.sh
    - export TC_DIR="../clang/" && bash buildkernel.sh
    - curl -sL https://git.io/file-transfer | sh
    - ./transfer wet topaz*.zip | tee transfer.log
    - cat transfer.log
    - rm -rf topaz*.zip
