---
env:
  TZ: Europe/London
task:
  name: Kernel compilation
  timeout_in: 60m
  container:
    image: nexgang/ubuntu:latest
    stateful: true
    greedy: true
    cpu: 4
    memory: 16G
  Setting-up-environment_script:
    - dir
    - ls
    - mkdir working
    - cd working
    - sudo apt-get update -y
    - sudo apt-get install make build-essential libncurses-dev bison flex elfutils
      libssl-dev libelf-dev ccache -y
    - sudo apt-get -y install locales
    - export LC_CTYPE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
  Building-kernel-clang_script:
    - mkdir compiler
    - cd compiler
    - mkdir -p ~/.bin
    - PATH="${HOME}/.bin:${PATH}"
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
    - chmod a+rx ~/.bin/repo
    - git config --global user.name "rk134"
    - git config --global user.email "me@rk134.cf"
    - repo init -u https://github.com/mvaisakh/android_kernel_manifest -b eva-oneplus-5.4 --depth=1
    - repo sync --no-tags --no-clone-bundle -j$(nproc --all)
    - rm -rf kernel/msm-5.4
    - git clone https://github.com/rk134/oneplus9pro --depth=1 -b lunaa-cbt kernel/msm-5.4
    - mkdir -p prebuilts-master/clang/host/linux-x86/clang-r450784d/
    - cd prebuilts-master/clang/host/linux-x86/clang-r450784d/
    - sudo apt install libarchive-tools
    - curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
    - bash antman -S=latest
    - bash antman --patch=glibc
    - cd ../../../../../
    - sed -i s/build-user/mvaisakh/g build/_setup_env.sh
    - sed -i s/build-host/statixos/g build/_setup_env.sh
    - sudo apt-get install libelf-dev libarchive-tools -y
    - BUILD_CONFIG=kernel/msm-5.4/build.config.msm.lahaina DEVICE=LUNAA VARIANT=nqgki COMPILER=clang LTO=thin BUILD_KERNEL=1 build/build.sh
    - cp out/msm-5.4-lahaina-nqgki/dist/Image ak3/
    - cat out/msm-5.4-lahaina-nqgki/dist/*.dtb > ak3/dtb
    - cp out/msm-5.4-lahaina-nqgki/dist/dtbo.img ak3/
    - cd ak3/ && zip -r9 eva-lunaa-$(/bin/date -u '+%d%m%Y%I%M')-gcc.zip * -x .git README.md ./*/placeholder
    - curl -sL https://git.io/file-transfer | sh
    - ./transfer wet eva-lunaa*-gcc.zip | tee transfer.log
    - cat transfer.log
    
